Vickuraa/Models/booking.cs
namespace Vickuraa.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("booking")]
    public partial class booking
    {
        public int bookingID { get; set; }

        public int scheduleID { get; set; }

        public int? customerID { get; set; }

        public int quantity { get; set; }

        [Required]
        public string receiverName { get; set; }

        [Required]
        public string receiverAddress { get; set; }

        public int receiverContactNo { get; set; }

        [Required]
        public string senderName { get; set; }

        public int senderContactNo { get; set; }

        public int packageID { get; set; }

        [Column(TypeName = "datetime2")]
        public DateTime date { get; set; }

        public int invoiceNo { get; set; }

        public int invoiceYear { get; set; }

        public int? RecievedPhysicalUser { get; set; }

        public DateTime? RecievedPhyscialDate { get; set; }

        public int? paymentRecievedUser { get; set; }

        public DateTime? paymentRecievedDate { get; set; }

        public int? receiptNo { get; set; }

        public int? receiptYear { get; set; }

        public int? dispatchedUser { get; set; }

        public DateTime? dispatchedDate { get; set; }

        public virtual package package { get; set; }

        public virtual schedule schedule { get; set; }

        public virtual user user { get; set; }
    }
}

Vickuraa/Controllers/bookingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vickuraa.Dto;
using Vickuraa.Models;

namespace Vickuraa.Controllers
{
    public class bookingsController : Controller
    {
        private vicukraaModel db = new vicukraaModel();


        public ActionResult RecievePackage(int Id)
        {

            booking booking = db.bookings.Find(Id);
            ViewBag.PackageDesc = booking.package.packageDesc;
            ViewBag.receiverName = booking.receiverName;
            ViewBag.RecieverAddress = booking.receiverAddress;
            ViewBag.senderName = booking.senderName;
            return View(booking);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RecievePackage(int BookingId, string senderName)
        {
            if (ModelState.IsValid)
            {
                var b = db.bookings.Where(a => a.bookingID == BookingId).FirstOrDefault();
                b.RecievedPhysicalUser = 4;
                b.RecievedPhyscialDate = DateTime.Now;
                b.paymentRecievedDate = DateTime.Now;
                b.paymentRecievedUser = 4;
                var ro = db.bookings.Where(a => a.receiptYear == DateTime.Now.Year).OrderByDescending(x => x.receiptNo).FirstOrDefault();
                if (ro.receiptNo == null)
                {
                    b.receiptNo = 0 + 1;
                }

                else
                {
                    b.receiptNo = ro.receiptNo + 1;
                }
               
                b.receiptYear = DateTime.Now.Year;
                db.Entry(b).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("PaidBookingList");
            }
            return View();
        }



        public ActionResult DispatchPackage(int Id)
        {

            booking booking = db.bookings.Find(Id);
            ViewBag.PackageDesc = booking.package.packageDesc;
            ViewBag.receiverName = booking.receiverName;
            ViewBag.RecieverAddress = booking.receiverAddress;
            ViewBag.senderName = booking.senderName;
            return View(booking);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DispatchPackage(int BookingId, string senderName)
        {
            if (ModelState.IsValid)
            {
                var b = db.bookings.Where(a => a.bookingID == BookingId).FirstOrDefault();
                b.dispatchedDate = DateTime.Now;
                b.dispatchedUser = 4;              
                db.Entry(b).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("PaidBookingList");
            }
            return View();
        }


        [HttpGet]
        public ActionResult PackageTimeLine(int Id)
        {

            var booking = db.bookings.Where(a => a.package.vesselID == Id).OrderByDescending(x => x.bookingID).FirstOrDefault();
            ViewBag.RequestedDate = booking.date;
            ViewBag.BoardedDate = booking.RecievedPhyscialDate;
            ViewBag.RecievedUser = booking.RecievedPhysicalUser;
            ViewBag.PaymentRecievedUser = booking.paymentRecievedUser;
            ViewBag.PaymentRecievedDate = booking.paymentRecievedDate;
            ViewBag.DispatchedDate = booking.dispatchedDate;
            ViewBag.DispatchedUser = booking.dispatchedUser;
            return View(booking);
        }

        // POST: bookings/Search
        [HttpGet, ActionName("Search")]
        public ActionResult Search()
        {
            List<destination> dest_list = db.destinations.ToList();
            ViewBag.destinations = new SelectList(db.destinations, "destinationID", "destinationName");
            return View("Search");
        }

        // POST: bookings/Search
        [HttpPost]
        public ActionResult searchconfirm(int fromID, int toID, DateTime date)
        {
            int routeid = 0;
            foreach (route rt in db.routes.ToList())
            {
                if (rt.departureportID == fromID)
                {
                    Debug.WriteLine("if");
                    if (rt.arrivalportID == toID)
                    {
                        Debug.WriteLine("double if");
                        routeid = rt.routeID;
                    }
                }
            }
            ViewBag.date = date.Date;
            ViewBag.From = db.destinations.Find(fromID).destinationName;
            ViewBag.To = db.destinations.Find(toID).destinationName;
            List<schedule> schedulelist = new List<schedule>();
            foreach (schedule sc in db.schedules.ToList())
            {
                if (sc.estimateDeparturetime.Date == date)
                {
                    // if(sc.routeID == routeid)
                    //  {
                    schedulelist.Add(sc);
                    // }
                }
            }
            ViewBag.schedulelist = schedulelist;
            ViewBag.Packages = db.packages.ToList();
            return View("SearchResult");
        }

        [HttpGet]
        public ActionResult viewDetails(int vesselids)
        {
            List<package> plist = new List<package>();
            foreach (package p in db.packages.ToList())
            {
                if (p.vesselID == vesselids)
                {
                    plist.Add(p);
                }
            }
            ViewBag.packages = plist;
            ViewBag.vessel = vesselids;
            return View("detailPackage");
        }

        [HttpPost]
        public ActionResult bookingCreate(int vessel)
        {

            ViewBag.vessel = vessel;
            return View("Create");
        }


        // GET: bookings
        public ActionResult PendingBookingList()
        {
            var bookings = db.bookings.Include(b => b.package).Include(b => b.schedule).Include(b => b.user)
                .Where(a => a.RecievedPhyscialDate == null);
            return View(bookings.ToList());
        }


        public ActionResult PaidBookingList()
        {
            var bookings = db.bookings.Include(b => b.package).Include(b => b.schedule).Include(b => b.user)
                .Where(a => a.paymentRecievedDate != null && a.dispatchedDate  == null);
            return View(bookings.ToList());
        }
        // GET: bookings/Details/5
        public ActionResult BookingDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            booking booking = db.bookings.Find(id);
            if (booking == null)
            {
                return HttpNotFound();
            }
            return View(booking);
        }


        public ActionResult SendPackage(int Id)
        {
            ViewBag.scheduleID = new SelectList(db.schedules, "scheduleID", "scheduleID");
            ViewBag.customerID = new SelectList(db.users, "userID", "username");
            ViewBag.packageTypeId = new SelectList(db.packageTypes, "packageTypeId", "packageType1");
            ViewBag.VesselId = Id;
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendPackage(PackageBooking packageBooking, int VesselId)
        {
            if (ModelState.IsValid)
            {
                var invoice = db.bookings.Where(a => a.invoiceYear == DateTime.Now.Year).OrderByDescending(c => c.invoiceNo).FirstOrDefault();
                var schedule = db.schedules.Where(a => a.vesselID == VesselId).OrderByDescending(c => c.scheduleID).FirstOrDefault();

                var package = new package();
                package.packageTypeId = packageBooking.packageTypeId;
                package.vesselID = VesselId;
                package.volume = packageBooking.volume;
                package.price = packageBooking.price;
                package.enteredDate = DateTime.Now;
                package.enteredUser = 1;
                db.packages.Add(package);
                {
                    var booking = new booking();
                    booking.customerID = 1;
                    booking.scheduleID = schedule.scheduleID;
                    booking.packageID = packageBooking.packageID;
                    booking.quantity = packageBooking.volume;
                    booking.receiverName = packageBooking.receiverName;
                    booking.receiverAddress = packageBooking.receiverAddress;
                    booking.receiverContactNo = packageBooking.receiverContactNo;
                    booking.receiverName = packageBooking.receiverName;
                    booking.receiverAddress = packageBooking.receiverAddress;
                    booking.receiverContactNo = packageBooking.receiverContactNo;
                    booking.senderContactNo = packageBooking.senderContactNo;
                    booking.senderName = packageBooking.senderName;
                    booking.date = DateTime.Now;
                    if (invoice == null)
                    {
                        booking.invoiceNo = 1;
                    }
                    else
                    {
                        booking.invoiceNo = invoice.invoiceNo + 1;

                    }
                    booking.invoiceYear = DateTime.Now.Year;
                    db.bookings.Add(booking);

                    db.SaveChanges();
                    return RedirectToAction("BookingList");
                }



            }
            return View(packageBooking);
        }

        public ActionResult EditBooking(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            booking booking = db.bookings.Find(id);
            if (booking == null)
            {

Vickuraa/Views/bookings/BookingDetails.cshtml
@model Vickuraa.Models.booking

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>booking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.package.packageID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.package.packageID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.schedule.scheduleID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.schedule.scheduleID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiverName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiverName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiverAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiverAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiverContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiverContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.senderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.senderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.senderContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.senderContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.invoiceNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.invoiceNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.invoiceYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.invoiceYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecievedPhysicalUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecievedPhysicalUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecievedPhyscialDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecievedPhyscialDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paymentRecievedUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paymentRecievedUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paymentRecievedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paymentRecievedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiptNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiptNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiptYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiptYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dispatchedUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dispatchedUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dispatchedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dispatchedDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.bookingID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Vickuraa/Views/bookings/CreateBooking.cshtml
@model Vickuraa.Models.booking

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>booking</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.scheduleID, "scheduleID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("scheduleID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.scheduleID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.customerID, "customerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("customerID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.customerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receiverName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.receiverName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.receiverName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receiverAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.receiverAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.receiverAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receiverContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.receiverContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.receiverContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.senderName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.senderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.senderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.senderContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.senderContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.senderContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.packageID, "packageID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("packageID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.packageID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.invoiceNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.invoiceNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.invoiceNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.invoiceYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.invoiceYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.invoiceYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecievedPhysicalUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecievedPhysicalUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecievedPhysicalUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecievedPhyscialDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RecievedPhyscialDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RecievedPhyscialDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paymentRecievedUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentRecievedUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentRecievedUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.paymentRecievedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.paymentRecievedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.paymentRecievedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receiptNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.receiptNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.receiptNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.receiptYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.receiptYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.receiptYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dispatchedUser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dispatchedUser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dispatchedUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dispatchedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dispatchedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dispatchedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Vickuraa/Views/bookings/Delete.cshtml
@model Vickuraa.Models.booking

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>booking</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.package.packageID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.package.packageID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.schedule.scheduleID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.schedule.scheduleID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.user.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiverName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiverName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiverAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiverAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiverContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiverContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.senderName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.senderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.senderContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.senderContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.invoiceNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.invoiceNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.invoiceYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.invoiceYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecievedPhysicalUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecievedPhysicalUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecievedPhyscialDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecievedPhyscialDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paymentRecievedUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paymentRecievedUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.paymentRecievedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.paymentRecievedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiptNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiptNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.receiptYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.receiptYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dispatchedUser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dispatchedUser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dispatchedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dispatchedDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Vickuraa/Views/bookings/Receive.cshtml
    <div>
        @using (@Html.BeginForm("confirmreceive", "bookings", FormMethod.Post))
        {
            <div style="text-align:center; margin: auto;">
                <h1>Receive</h1>
                <div style="padding:10px;">
                    @Html.DropDownList("bookingID", (IEnumerable<SelectListItem>)ViewBag.booking, "Bookings", new { @class = "form-control" })
                    <br />
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Received" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }
    </div>